config:
  propagate_socket: "/var/run/docker.sock"

rules:
  acls:
    - match:
        path: "/v1.*/volumes"
        method: "GET"
      action: "deny"
      reason: "Listing volumes is restricted"

    - match:
        path: "/v1.*/containers/create"
        method: "POST"
        contains:
          Env:
            - "BLOCK=true"
      action: "deny"
      reason: "Blocked creation of containers with restricted env variables"

    - match:
        path: "/_.*"
        method: ".*"
      action: "allow"
      reason: "Allow metadata requests"

    - match:
        path: "/.*"
        method: ".*"
      action: "allow"

  rewrites:
    - match:
        path: "/v1.*/containers/create"
        method: "POST"
      patterns:
        - field: "Env"
          action: "upsert"
          value: "FUN=yes"
        - field: "Env"
          action: "replace"
          match: "DEBUG=true"
          value: "DEBUG=false"
        - field: "HostConfig.Privileged"
          action: "replace"
          match: true
          value: false
        - field: "Env"
          action: "delete"
          match: "PANTS=*"
