config:
  propagate_socket: "/var/run/docker.sock"

rules:
  acls:
    - match:
        path: "/v1.*/volumes"
        method: "GET"
      action: "deny"
      reason: "Listing volumes is restricted"

    - match:
        path: "/v1.*/containers/create"
        method: "POST"
        contains:
          Env:
            - "BLOCK=true"
      action: "deny"
      reason: "Blocked creation of containers with restricted env variables"

    - match:
        path: "/_.*"
        method: ".*"
      action: "allow"
      reason: "Allow metadata requests"

    - match:
        path: "/.*"
        method: ".*"
      action: "allow"

  rewrites:
    - match:
        path: "/v1.*/containers/create"
        method: "POST"
      actions:
        - action: "upsert"
          update:
            Env:
              - "FUN=yes"
        - action: "replace"
          contains:
            Env:
              - "DEBUG=true"
          update:
            Env:
              - "DEBUG=false"
        - action: "replace"
          contains:
            HostConfig:
              Privileged: true
          update:
            HostConfig:
              Privileged: false
        - action: "delete"
          contains:
            Env:
              - "PANTS=.*"
