site_name: Docker Socket Proxy
site_description: A secure proxy for Docker socket with fine-grained access control
site_author: John Murphy
site_url: https://github.com/yourusername/docker-socket-proxy

repo_name: js-murph/docker-socket-proxy
repo_url: https://github.com/js-murph/docker-socket-proxy
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration:
      - Overview: configuration/index.md
      - Rules: configuration/rules.md
      - Examples: configuration/examples.md
  - API Reference: api-reference.md
  - CLI Reference: cli-reference.md
  - Contributing: contributing.md
