name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Run unit tests
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Run integration tests
        run: INTEGRATION_TEST=true go test -v ./internal/integration/...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
